package POJOS;
// Generated 13-jun-2022 21:39:47 by Hibernate Tools 4.3.1



/**
 * Retenciones generated by hbm2java
 */
public class Retenciones  implements java.io.Serializable {


     private String nombreEmpleado;
     private String nombreDepartamento;
     private int salarioBruto;
     private int retencion;
     private int salarioNeto;

    public Retenciones() {
    }

    @Override
    public String toString() {
        return "Retenciones{" + "nombreEmpleado=" + nombreEmpleado + ", nombreDepartamento=" + nombreDepartamento + ", salarioBruto=" + salarioBruto + ", retencion=" + retencion + ", salarioNeto=" + salarioNeto + '}';
    }

    public Retenciones(String nombreEmpleado, String nombreDepartamento, int salarioBruto, int retencion, int salarioNeto) {
       this.nombreEmpleado = nombreEmpleado;
       this.nombreDepartamento = nombreDepartamento;
       this.salarioBruto = salarioBruto;
       this.retencion = retencion;
       this.salarioNeto = salarioNeto;
    }
   
    public String getNombreEmpleado() {
        return this.nombreEmpleado;
    }
    
    public void setNombreEmpleado(String nombreEmpleado) {
        this.nombreEmpleado = nombreEmpleado;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public int getSalarioBruto() {
        return this.salarioBruto;
    }
    
    public void setSalarioBruto(int salarioBruto) {
        this.salarioBruto = salarioBruto;
    }
    public int getRetencion() {
        return this.retencion;
    }
    
    public void setRetencion(int retencion) {
        this.retencion = retencion;
    }
    public int getSalarioNeto() {
        return this.salarioNeto;
    }
    
    public void setSalarioNeto(int salarioNeto) {
        this.salarioNeto = salarioNeto;
    }




}


